"""sync_all_models

Revision ID: aa081816a75c
Revises: 0001_initial_schema
Create Date: 2026-09-30 19:58:58.493563
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aa081816a75c'
down_revision: Union[str, None] = '0001_initial_schema'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('sessions_session_token_key'), 'sessions', type_='unique')
    op.drop_index(op.f('ix_sessions_session_token'), table_name='sessions')
    op.create_index(op.f('ix_sessions_session_token'), 'sessions', ['session_token'], unique=True)
    op.add_column('stockpile_items', sa.Column('completed_quantity', sa.Integer(), nullable=False))
    op.add_column('stockpiles', sa.Column('creator_id', sa.String(length=64), nullable=True))
    op.add_column('stockpiles', sa.Column('assignee_id', sa.String(length=64), nullable=True))
    op.add_column('stockpiles', sa.Column('status', sa.String(length=32), nullable=False))
    op.add_column('stockpiles', sa.Column('destination', sa.String(length=255), nullable=False))
    op.add_column('stockpiles', sa.Column('notes', sa.Text(), nullable=True))
    op.create_index(op.f('ix_stockpiles_status'), 'stockpiles', ['status'], unique=False)
    op.drop_column('stockpiles', 'location')
    op.drop_column('stockpiles', 'name')
    op.drop_column('stockpiles', 'last_updated_by')
    op.drop_column('stockpiles', 'code')
    op.drop_constraint(op.f('users_discord_id_key'), 'users', type_='unique')
    op.drop_index(op.f('ix_users_discord_id'), table_name='users')
    op.create_index(op.f('ix_users_discord_id'), 'users', ['discord_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_discord_id'), table_name='users')
    op.create_index(op.f('ix_users_discord_id'), 'users', ['discord_id'], unique=False)
    op.create_unique_constraint(op.f('users_discord_id_key'), 'users', ['discord_id'], postgresql_nulls_not_distinct=False)
    op.add_column('stockpiles', sa.Column('code', sa.VARCHAR(length=64), autoincrement=False, nullable=True))
    op.add_column('stockpiles', sa.Column('last_updated_by', sa.VARCHAR(length=64), autoincrement=False, nullable=True))
    op.add_column('stockpiles', sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.add_column('stockpiles', sa.Column('location', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_stockpiles_status'), table_name='stockpiles')
    op.drop_column('stockpiles', 'notes')
    op.drop_column('stockpiles', 'destination')
    op.drop_column('stockpiles', 'status')
    op.drop_column('stockpiles', 'assignee_id')
    op.drop_column('stockpiles', 'creator_id')
    op.drop_column('stockpile_items', 'completed_quantity')
    op.drop_index(op.f('ix_sessions_session_token'), table_name='sessions')
    op.create_index(op.f('ix_sessions_session_token'), 'sessions', ['session_token'], unique=False)
    op.create_unique_constraint(op.f('sessions_session_token_key'), 'sessions', ['session_token'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###